---
title: Checking a package
layout: default
output: bookdown::html_chapter
---

# Automated checking {#check}

R provides a number of automated checks for the quality of your code. These are known as `R CMD check`. If you're planning on submitting to CRAN, it is essential that you run `R CMD check`, but it's also useful to run even if you're not.

`R CMD check` emits three types of message:

* `ERROR`: These are definite problems and you should fix regardless of whether
  or not you're submitting to CRAN.
  
* `WARNING`: These are likely problems. You must fix if you're planning to 
  submit to CRAN, and it's a good idea to look into them even if you're not.
  
* `NOTE`: These are sometimes false positives, so if you're not planning on 
  submitting to CRAN, you might not need to fix. If you are submitting to
  CRAN you should work around them. It is possible to argue you way around
  them, but that requires human intervention. It's almost always better to 
  fix them so they don't appear. 

`R CMD check` is frustrating the first time you run it - you'll probably discover many problems that you need to fix. The key to making `R CMD check` less frustrating is to run it more often. The sooner you find out about a problem after making it, the easier it is to fix. The limit of this approach is to run `R CMD check` every time you make a change, and in fact you'll learn how to do that with travis, an automated continuous integration tool.

## Workflow

To check your package, run `devtools::check()`, or in RStudio, press Cmd + Shift + E.

I recommend using these tools instead of running `R CMD check` from the console because `devtools::check()`:

* Documents the package first.

* Checks a built package. This is the recommend check process to avoid 
  spurious local temporary artefacts (like compilation artefacts).

* Sets a consistent locale.

* Ensures that you're using the same version of R that you're currently running.

* Provides arguments to make `R CMD check` run as closely as possible to 
  CRAN.

* Sets the `NOT_CRAN` environment variable which allows you to selectively
  skip tests on CRAN.

## Checks

I don't recommend reading the list of checks exhaustively. Instead, if one of the checks fails, come back here for a simple explanation of what the problem is, and how you might go about fixing it. Common problems described in individual chapters. Provide comprehensive listing here with backlinks to individual chapters.

The checks change with each version of R, so you may want to consult the most recent version of this chapter online: <http://r-pkgs.had.co.nz/check.html>

### Check metadata

<!--

The first few lines describe the checking environment. I'm running R 3.1.1 on OS X with UTF-8 charset.

* __Using log directory__ ‘/Users/hadley/Documents/web/httr.Rcheck’
* __Using R version__ 3.1.1 (2014-07-10)
* __Using platform__: x86_64-apple-darwin13.1.0 (64-bit)
* __Using session charset__: UTF-8

Next the description is parsed and the package version is printed. Here I'm checking the version 0.5.0.9000 (you'll learn more about that weird version number in XXXX) of the httr package.

* __Checking for file__ ‘httr/DESCRIPTION’
* __This is package__ ‘httr’ __version__ ‘0.5.0.9000’

### Package structure

* __Checking package namespace information__.

* __Checking package dependencies__.

* __Checking if this is a source package__.

* __Checking if there is a namespace__. You must have a `NAMESPACE` file.
  Roxygen2 will create this for you as described in [namepsaces](#namespace).

* __Checking for executable files__. Packages should not contain any executable
  files.

* __Checking for hidden files and directories__. Files and directories starting
  with `.` usually represent a mistake - typically you should delete them,
  but if they do belong in the source package, use `.Rbuildignore` to make
  sure they're not in the built package. R automatically removes common source
  code manager directories like `.git` and `.svn`.

<!-- https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L381 -->
* __Checking for portable file names__.  Stick to letters, numbers and 
  underscores and dashes. Avoid non-English letters and spaces. The total length
  of a path must be less than 100 characters. Don't use any of 
  aux, com1-com9, con, lpt1-lpt9, nul, prn.
  
<!-- https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L541 -->
* __Checking for sufficient/correct file permissions__. All files should be
  readable by the current user. If you have a `configure` file, it must be
  executable. Fix these problems.

* __Checking whether package ‘httr’ can be installed__. `R CMD check` runs
  `R CMD install` to make sure that it's possible to install the package. If 
  this fails, you should run `devtools::install()` or RStudio's Build & Reload
  to see the error messages.

* __Checking installed package size__. Packages should not be "too" big. 
  One common problem is that you haven't adequately compressed the data; see 
  [data](#data-cran) for more details. Another common problem is large 
  vignettes; see [vignette CRAN notes](#vignette-cran) for more details.

* __Checking package directory__.

<!-- https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L597 -->
* __Checking DESCRIPTION meta-information__. Checks encoding. Checks license.
  Checks has maintainer.

<!-- https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L746 -->
* __Checking top-level files__. Checks that only standard files and directories
  are found at the top level of the package. Either move the directory to `inst/`
  if it should be available in installed package, or remove from built packages 
  with `devtools::add_build_ignore()` it it shouldn't.

<!-- https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L859 -->
* __Checking for left-over files__. These files are likely to be included
  in error, so you probably should just delete them. In the unlikely event that 
  you actually needed them, use `devtools::add_build_ignore()`.

<!-- https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L877 -->
* __Checking index information__. Usually R automatically generates the 
  `INDEX` file that's used to generate package help (e.g. 
  `help(package = base)`). It is possible to generate it by hand, and this 
  check makes sure you've listed all functions in the package.

<!-- https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L924 -->
* __Checking package subdirectories__. 

    * Checks that you don't have empty directories
    * Case of the directories is correct (e.g. uppercase R, lowercase everything 
      else)
    * Make sure you haven't accidentally include a check directory. 
    * Checks that directories in `inst` don't overwrite existing files.
    * Checks citation is valid and in correct location.

### R code


<!-- https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L1226 -->
* __Checking R files for non-ASCII characters__. For maximum portability (i.e.
  so people can use your package on Windows) you should avoid using non-ASCII
  characters in R files. It's ok to use them in comments, but object names 
  shouldn't use them, and in strings you should use unicode escapes. See XXX
  for more deatils.

* __Checking R files for syntax errors__. Obviously your R code must be valid.
  You're unlikely to see this error if you're been regularly using 
  `devtools::load_all()`.

* __Checking dependencies in R code__. Any errors here indicate that forgotten
  to declare a needed package in the `DESCRIPTION`. Remember that you should
  never use `require()` or `library()` inside a package - see 
  [namespace imports](#imports) for more details on best practices.

* __Checking S3 generic/method consistency__. S3 methods must have compatible 
  method signatures to their generic. This means that the method must have the 
  same arguments as its generic, with one exception. If the generic  includes 
  `...` you can have additional arguments. A common cause of this error is 
  defining print methods, because the `print()` generic contains`...`.
  
    ```{r}
    print
    
    # BAD
    print.my_class <- function(x) cat("Hi")
    
    # GOOD
    print.my_class <- function(x, ...) cat("Hi")
    ```

* __Checking replacement functions__. Replacement functions (e.g. functions that
  are called like `foo(x) <- value`, must have value as the last argument.

* __Checking R code for possible problems__. This is a catch all for
  a wide range of problems:

    * You must use `TRUE` and `FALSE` in your code and examples, not `T` and 
      `F`.
    
    * `R CMD check` uses the codetools package to make sure that your functions
      don't accidentally use variables that don't exist. This sometimes raises 
      false positives if you're using non-standard evaluation (NSE) functions 
      like `subset()` or `with()`. Generally, I think you should avoid NSE in 
      package functions, and hence avoid this NOTE, but if there is no 
      standard evaluation version, see `?globalVariables` to suppress the
      NOTE.
      
    * You can't refer to internal functions in other packages with `:::`.

### Package loading and unloading

* __Checking whether the package can be loaded__. R loads your package with
  `requireNamespace()`. Failure here typically indicates a problem with 
  `.onLoad()`.

* __Checking whether the package can be loaded with stated dependencies__.
  R loads your package inside a special library that only contains the 
  packages listed in `DESCRIPTION`. Failure here typically indicates that 
  you're missing a dependency.

* __Checking whether the package can be unloaded cleanly__. Check `.onUnload()`.

* __Checking whether the namespace can be loaded with stated dependencies__.

* __Checking whether the namespace can be unloaded cleanly__.

* __Checking loading without being on the library search path__.

### Documentation

You can run the most common of these outside `R CMD check` with `devtools::check_doc()` (which automatically calls `devtools::document()` for you). If you have documentation problems, it's best to iterate quickly with `check_doc()`. 

* __Checking Rd files__. This checks that all `man/*.Rd` use the correct
  Rd syntax. If this fails for you, it indicates a bug in roxygen2. Please 
  let me know.

* __Checking Rd metadata__.

* __Checking Rd line widths__.  Lines in RD files must be less than 90 
  characters wide. This is unlikely to occur if you wrap your roxygen 
  comments to 80 characters wide. For very long urls, use a link-shortening
  service like [bit.ly](http://bit.ly).

* __Checking Rd cross-references__. These typically represent typos.
  Also recall the syntax for linking to functions in other packages: 
  `\link[package]{function}`. Sometimes I accidentally flip `\code{}` and
  `\link{}`: `\link{\code{function}}` will not work.

* __Checking for missing documentation entries__. All exported objects must 
  be documented. All paramters of functions must be documented.

* __Checking for code/documentation mismatches__. This make sure that 
  documentation matches the code. This should never fail because you're using
  roxygen2 which automatically keeps them in sync.

* __Checking Rd `\usage` sections__.

* __Checking Rd contents__.

* __Checking for unstated dependencies in examples__. If you use a package 
  only for an example, make sure it's listed in the `Suggests` field. Before
  running example code that depends on it, test to see if it's available with
  `requireNamespace("pkg", quietly = TRUE)`.

* __Checking examples__. Every documentation example must run without errors,
  and must not take too long. Exclude failing or slow tests with `\donttest{}`.
  See [documenting functions](#man-functions) for more details.
  
    A common cause of problems is relying on internal functions - examples can 
    only use exported functions.
    
    Examples are one of the last checks run, so first them can be painful if
    you have to run `devtools::check()` each time. Instead, use 
    `devtools::run_examples()`: it only checks the examples, and has an optional 
    parameter which tells it which function to start at - that way once you've 
    discovered an error, you can rerun from just that file, not all the 
    files that lead up to.

## Compiled code

* __Checking foreign function calls__. `.Call()`, `.C()`, `.Fortran()`, 
  `.External()` must always be called either with a `NativeSymbolInfo` object
  (as created with `@useDynLib`) or use the `.package` argument.

* __Checking line endings in C/C++/Fortran sources/headers__. Always
  use `\n` as a line ending.

* __Checking line endings in Makefiles__. As above.

* __Checking for portable use of `$(BLAS_LIBS)` and `$(LAPACK_LIBS)`__.

* __Checking compiled code__.

### Tests

* __Checking for unstated dependencies in tests__. Every package used by tests 
  must be included in the dependency fields. If the package is only used in the 
  tests (and not elsewhere in the package), list it in the `Suggests` field.

* __Checking tests__.  Each file in `tests/` is run. If you've followed the 
  instructions in [testing](#tests) you'll have at least one file: 
  `testthat.R`. Failing here is an ERROR.

### Vignettes

<!-- https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L718 -->
* __Checking ‘build’ directory__. Used to track vignette builds. I'm not
  sure how this could fail unless you've accidentally `.Rbuildignore`d a file.

* __Checking installed files from ‘inst/doc’__.

* __Checking files in ‘vignettes’__.

* __Checking for unstated dependencies in vignettes__. As with tests, every
  package that you use in a vignette must be listed in the `DESCRIPTION`. 
  If a package is used only for a vignette, and not elsewhere, make sure 
  it's listed in `Suggests`.

* __Checking package vignettes in ‘inst/doc’__. This checks that every source
  vignette (i.e. `.Rmd`) has a built equivalent (i.e. `.html`) in `inst/doc`. 
  This shouldn't fail if you've used the standard process outlined in 
  [vignettes](#vignettes). If there is a problem, start by checking your
  `.Rbuildignore`.

* __Checking running R code from vignettes__. The R code from each vignette 
  is run. If you want to deliberately execute errors (to show the user what 
  failure looks like), make sure the chunk has `error = TRUE, purl = FALSE`.

* __Checking re-building of vignette outputs__. Each vignette is re-knit to
  make sure that the output corresponds to the input. Again, this shouldn't
  fail in normal circumstances.
  
* __Checking PDF version of manual__. Occassionally you'll get an error when 
  building the PDF manual. This is usually because the pdf is built by latex and 
  you've forgotten to escape something. Debugging this is painful - your best 
  bet is to look up the latex logs and combined tex file and work back from 
  their to `.Rd` files then back to a roxygen comment. I consider any such
  failure to be a bug in roxygen2, so please let me know.

To run vignettes, the package first must be installed. That means R:

* Installs the package without vignettes.
* Builds all the vignettes.
* Re-installs the package with vignettes.

If you have a lot of compiled code, this can be rather slow. You may want to use `--no-build-vignettes`

## Checking after every commit with Travis

If you use [git and github](#git), I recommend exploring the very useful [Travis CI](https://travis-ci.org/). Travis is a continuous integration service which means it will run code of your choosing every time you push a commit to github. 

1.  Run `use_travis()` to set up a basic `.travis.yml` config file. The 
    defaults are usually adequate for simple packages.

1.  Navigate to your [account](https://travis-ci.org/profile) and enable
    travis for the repo you want to test on.

1.  Commit and push to github.

1.  Wait a few minutes to see the results in your email.

Now you're set up so that `R CMD check` will be run every time you push a commit to github, and every time some one does a pull request.  Any time a failure occurs you'll find out about it right away. I find this really useful - it also encourages me to run `R CMD check` more frequently locally, because I know if it fails I'll find out about a few minutes later, often once I've moved on to a new challenge.

Common configuration:

* Fail not only on errors, but also on warnings
* Install binary packages
* Install github packages

Since you can use Travis to run arbitrary code you can use it to implement arbitrary push-to-deploy strategies. For example, it's relatively easy to deploy code to S3 - this makes it easy (for example) to update a documentation website.
