## Copyright

Before we talk about licenses, it's important to talk a little about copyright, because copyright is the legal framework that underpins open source licenses.
Here we'll focus on US copyright law because that's what we're most familiar with.
The broad strokes are similar across most countries, but the details will differ so you should also look for a copyright guide for your country.
(And, again, if you're making any important business decisions, you should consult a local lawyer.)

### Copyright and software

In the US, copyright grants the copyright holder[^copyright-1] six exclusive rights[^copyright-2] to any creative work
. Three of the rights apply to software
[^copyright-3]:

[^copyright-1]: This is usually the author, but not always.
    More on that shortly.

[^copyright-2]: <https://www.law.cornell.edu/uscode/text/17/106>

[^copyright-3]: The other rights apply to things that you can perform (like plays) and sound recordings.

-   To *reproduce* the work in copies.

-   To prepare *derivative works* based upon the work.

-   To *distribute* copies of the work to the public by sale or other transfer of ownership, or by rental, lease, or lending.

To express this a little more pithily, only the author has right to **copy**, **modify**, and **share** their code.
These exclusive rights are strict: if code doesn't have a license, you're not allowed to copy it, modify it, or share it with others.

There are some limitations to these exclusive rights, but only one applies to software: fair use[^copyright-4].
Defining fair use is hard, and doesn't apply much in software development.
It does, however, mean that it's usually OK to include a snippet of open source code in a presentation slide without having worry about the license.

[^copyright-4]: The others include things like the right to perform a play in a face-to-face classroom, or you're allowed to sell books that you own, and its ok for authorized companies to make accessible versions.

Fortunately, while these rights are the default, the copyright holder can choose to relax them if they want.
The goal of open source licenses is to provide a set of standard way of relaxing these rights to make sure that as many people as possible can copy, modify, and share open source code.

Who is the copyright holder?
If it's something you do as an employee, in the scope of your employment, your employer owns it.
If it's a contract, you own it, unless you've explicitly agree otherwise (see <http://worksmadeforhire.com> for more details).
If it's something you do for yourself in your free time, you own it.

### Derivative work

Understanding what it means to copy or distribute code.
But what does it mean to modify it to create a derivative work?
No hard and fast rules.

What is a derivative work?

-   Fixing a bug

-   Translating to another programming language.

-   In some cases, rewriting an algorithm might be considered a derivative work, even if none of the original code is included.

-   Forking

-   Including as is probably isn't a derivative work

What isn't a derivative work?

-   Merely using code is not sufficient to make a derivative work. That means that R code that you write to perform a data analysis is not a derivative work.

Derivative work: <https://www.linuxjournal.com/article/6366>.
