---
layout: default
title: Installed files
output: bookdown::html_chapter
---

In some sense `inst/` is the opposite of `.Rbuildignore` - where`.Rbuildignore` lets you remove arbitrary files and directories to the top-level, `inst/` lets you add them.

Never use `inst/build`, `inst/R`, `inst/data`, `inst/demo`, `inst/exec`, `inst/inst`, `inst/man`, `inst/po`, `inst/src`, `inst/tests`, `inst/tools` and `inst/vignettes`.

Use `system.file()` to access files in `inst/`.

* `inst/COPYRIGHTS`, `inst/AUTHORS`

* `inst/doc`: where vignettes used to live. Modern packages should never have
  a `inst/doc`.
  
* `inst/extdata`: additional external data for examples and vignettes. 
  See [external data](#data-extdata) for more detail.
  
### Other languages  

* `inst/python`, `inst/perl`, `inst/tcl` etc: scripts written in other
  programming languages. (Could also go in `exec/`). "If your package requires one of these interpreters or an extension then this should be declared in the ‘SystemRequirements’ field of its DESCRIPTION file"
  
* `inst/java`: "Java code is a special case: except for very small programs, .java files should be byte-compiled (to a .class file) and distributed as part of a .jar file: the conventional location for the .jar file(s) is inst/java. It is desirable (and required under an Open Source license) to make the Java source files available: this is best done in a top-level java directory in the package—the source files should not be installed."

### Package citation

The `CITATION` file lives in the `inst` directory and is intimately connected to the `citation()` function which tells you how to cite R and R packages.  Calling `citation()` without any arguments tells you how to cite base R:

    To cite R in publications use:

      R Core Team (2012). R: A language and environment for statistical
      computing. R Foundation for Statistical Computing, Vienna, Austria.
      ISBN 3-900051-07-0, URL http://www.R-project.org/.

    A BibTeX entry for LaTeX users is

      @Manual{,
        title = {R: A Language and Environment for Statistical Computing},
        author = {{R Core Team}},
        organization = {R Foundation for Statistical Computing},
        address = {Vienna, Austria},
        year = {2012},
        note = { {ISBN} 3-900051-07-0},
        url = {http://www.R-project.org/},
      }

    We have invested a lot of time and effort in creating R, please cite it
    when using it for data analysis. See also ‘citation("pkgname")’ for
    citing R packages.

This is generated from a `CITATION` file that looks like this:

    bibentry("Manual",
       title = "R: A Language and Environment for Statistical Computing",
       author = person("R Core Team"),
       organization = "R Foundation for Statistical Computing",
       address      = "Vienna, Austria",
       year   = version$year,
       note   = "{ISBN} 3-900051-07-0",
       url    = "http://www.R-project.org/",
  
       mheader = "To cite R in publications use:",

       mfooter = 
         paste("We have invested a lot of time and effort in creating R,",
          "please cite it when using it for data analysis.",
          "See also", sQuote("citation(\"pkgname\")"),
          "for citing R packages.", sep = " ")
    )

As you can see, it's pretty simple: you only need to learn one new function, `bibentry()`. The most important arguments, are `bibtype` (the first argument, which can "Article", "Book", "PhDThesis" and so on), and then the standard bibliographic information like `title,`, `author`, `year`, `publisher`, `journal`, `volume`, `issue`, `pages` and so on (they are all described in detail in `?bibentry`). The header (`mheader`) and footer (`mfooter`) are optional, and are useful places for additional exhortations.

