# Preface {#sec-preface .unnumbered}

```{r, echo = FALSE}
source("common.R")
status("restructuring")
```

Welcome to the 2nd edition of R Packages!
If you're familiar with the 1st edition, this preface describes the major changes so that you can focus your reading on the new areas.

There are X main goals for this edition:

-   Update to reflect changes in the devtools package, specifically, its ["conscious uncoupling"](https://www.tidyverse.org/articles/2018/10/devtools-2-0-0/#conscious-uncoupling) into a set of smaller, more focused packages.

-   Expanded coverage of workflow and process, alongside the presentation of all the important moving parts that make up an R package.

-   *more to come*

Specifics about individual chapters:

-   New @sec-whole-game, "The Whole Game", previews key steps in the package development process.

-   New @sec-setup, "Setup", has been carved out of the previous Introduction and gained more detail.

-   The sections "Organising your functions" and "Code style", from @sec-r, "R code", have been removed, in favor of an online style guide, <https://style.tidyverse.org/>.
    The style guide is paired with the new styler package [@styler] which can automatically apply many of the rules.

-   The chapter formerly known as "Package structure" has been expanded and split into two chapters, one covering package structure and state (@sec-package-structure-state) and another on workflows and tooling (@sec-workflows101).

-   The chapters on Git/GitHub and C/C++ have been removed.
    These didn't have quite enough information to be useful, and since the first edition of the book, other resources have arisen that are better learning resources.

-   The very short `inst` chapter has been combined into @sec-misc, with all the other directories that are of relatively minor importance.
