---
layout: default
title: R code
output: bookdown::html_chapter
---

# R code

The `R/` directory contains all your R code, so copy in any existing code.  Files containing R code should always have the extension `.R` (you can also use `.r`, but I recommend sticking to `.R` for consistency).

It's up to you how you arrange your functions into files. There are two
possible extremes: all functions in one file, and each function in its own
file. I think these are both too extreme, and I suggest grouping related
functions into a single file. My rule of thumb is that if I can't remember
which file a function lives in, I probably need to split them up into more
files: having only one function in a file is perfectly reasonable,
particularly if the functions are large or have a lot of documentation. As
you'll see in the next chapter, often the code for the function is small
compared to its documentation (it's much easier to do something than it is to
explain to someone else how to do it.)

## Starting a package

There are two ways to get started with a new package:

* Firstly, you can just create an R directory and move in your R code.

* Alternatively, use `devtools::create("pkgname")`: this will create a
  directory called `pkgname`, containing an empty `R/` directory and 
  some useful files that you'll learn about in the course of this book.

__Never__ use `package.skeleton()`: it's designed for a bygone era of package development, and mostly serves to make your life harder, not easier.

## RStudio projects

If you use RStudio, I highly recommend using an RStudio project for your package:

* Projects isolate state so that unrelated things stay unrelated.

* You get handy code navigation tools like `F2` to jump to a function
  definition and `Ctrl + .` to look up functions by name.

* You get useful keyboard shortcuts for common package development tasks.
  See Help | Keyboard shortcuts, or press Alt + Shift + K to see them all.

* Projects are a light weight text file, and devtools makes sure that 
  it's not included in binary packages that you share with others 
  (by including in `.Rbuildignore`).

`create()` will automatically create a `.Rproj` file for you. To create one after the fact, run `devtools::use_rstudio()` in the package directory.

## Loading code

The first advantage of using a package is that it's now easier to reload all of your code. There are two options: 

* `load_all()`, Cmd + Shift + L, reloads all code in the package. It's 
  fast but takes some shortcuts that occassionally backfire. In Rstudio,
  this also saves all open files, saving you a key press.

* Build & reload, Cmd + Shift + B. This is only available in Rstudio, because
  it installs the package, then restarts R, then loads the package with 
  `library()` (If you don't use Rstudio, you'll have to do this by hand;
  that's a bit painful.)

These commands make it very easy to iterate between writing code in your editor and trying it out in the R console.

## Development cycles

The package development cycle describes the sequence of operations that you use when developing a package. You probably already have a sequence of operations that you're comfortable with when developing a single file of R code. It might be:

1. Try something out on the command line.

1. Modify it until it works and then copy and paste the command into an R file.

1. Every now and then restart R and reload the complete file to make sure
   you've ordered all the code correctly.

Or maybe you:

1. Write all your functions in an R file and save it.

1. `source()` the file into your current session.

1. Interactively try out the functions and see if they return the correct
  results.

1. Repeat the above steps until the functions work the way you expect.

With devtools and Rstudio, you can:

1. Edit R files in the editor.

1. Press Cmd + Shift + L

1. Explore the code in the console

1. Rinse and repeat.

You might also be a little bit more worried about checking that your functions work, not only now, on your computer, but also in the future and on other computers. You'll learn more about more sophisticated workflows that prevent that from happening in [testing](#tests).


## Source, binary and bundled packages

So far we've just described the structure of a source package: the development version of a package that lives on your computer. There are also two other types of package: bundled packages and binary packages.

A package __bundle__ is a compressed version of a package in a single file. By convention, package bundles in R use the extension `.tar.gz`. This is Linux convention indicating multiple files have been collapsed into a single file (`.tar`) and then compressed using gzip (`.gz`). The package bundle is useful if you want to manually distribute your package to another R package developer. It is not OS specific. You can use `devtools::build()` to make a package bundle.

If you want to distribute your package to another R user (i.e. someone who doesn't necessarily have the development tools installed) you need to make a __binary__ package. Like a package bundle, a binary package is a single file, but if you uncompress it, you'll see that the internal structure is a little different to a source package: 

* a `Meta/` directory contains a number of `Rds` files. These contain cached
  metadata about the package, like what topics the help files cover and
  parsed versions of the `DESCRIPTION` files. (If you want to look at what's
  in these files you can use `readRDS`)

* a `html/` directory contains some files needed for the HTML help.

* there are no `.R` files in the `R/` directory - instead there are three
  files that store the parsed functions in an efficient format. This is
  basically the result of loading all the R code and then saving the
  functions with `save`, but with a little extra metadata to make things as
  fast as possible.

* If you had any code in the `src/` directory there will now be a `libs/`
  directory that contains the results of compiling that code for 32 bit
  (`i386/`) and 64 bit (`x64`)

Binary packages are platform specific: you can't install a Windows binary package on a Mac or vice versa. You can use `devtools::build(binary = TRUE)` to make a package bundle.

An __installed__ package is just a binary package that's been uncompressed into a package library, described next.

## Package libraries

A library is a collection of installed packages. You can have multiple libraries on your computer and most people have at least two: one for the recommended packages that come with a base R install (like `base`, `stats` etc), and one library where the packages you've installed live. The default is to make that directory dependent on which version of R you have installed - that's why you normally lose all your packages when you reinstall R. If you want to avoid this behaviour, you can manually set the `R_LIBS` environmental variable to point somewhere else. `.libPaths()` tells you where your current libraries live.

When you use `library(pkg)` to load a package, R looks through each path in `.libPaths()` to see if a directory called `pkg` exists. 

## Installing packages

Package installation is the process whereby a source package gets converted into a binary package and then installed into your local package library.  There are a number of tools that automate this process:

* `install.packages()` installs a package from CRAN. Here CRAN takes care of
  making the binary package and so installation from CRAN basically is
  equivalent to downloading the binary package value and unzipping it in
  `.libPaths()[1]` (but you should never do this by hand because the process
  also does other checks)

* `devtools::install()` installs a source package from a directory on your
  computer.

* `devtools::install_github()` installs a package that someone has published
  on their [github](http://github) account. There are a number of similar
  functions that make it easy to install packages from other internet
  locations: `install_url`, `install_gitorious`, `install_bitbucket`, and so
  on.

## Exercises

* Go to CRAN and download the source and binary for XXX. Unzip and compare.
  How do they differ?

* Download the __source__ packages for XXX, YYY, ZZZ. What directories do they
  contain?

* Where is your default library? What happens if you install a new package
  from CRAN?

