---
title: Releasing a package
layout: default
output: bookdown::html_chapter
---

# Releasing a package {#release}

If you want your package to have significant traction in the R community, you need to submit it to CRAN. Submitting to CRAN is a lot more work than just providing a version on github, but the vast majority of R users do not install packages from github. The CRAN submission process can be frustrating, but it's worthwhile, and this chapter will make it as painless as possible.

Follow these steps when your package is ready for release:

1. Pick a version.
1. Update `README.md` and `NEWS.md`.
1. Document your `R CMD check` process.
1. Submit the package to CRAN.
1. Prepare for the next version.
1. Publicise the new version.

## Version

If you're following the advice in [version](#version), the version number will look like `1.0.0.9000`. Now you need to look at the changes you've made and decide if this will be version `1.0.1`, `1.1.0`, or `2.0.0`:
  
  * For a patch, increment the third component, `1.0.1`. This for 
    show-stopping bugs that need to be fixed ASAP.
  
  * For backward compatible changes, increment the second component, `1.1.0`. 
    If you've added new features and fixed bugs in such a way that existing code 
    should continue work, increment the second component. This is the most
    common type of release. It's perfectly fine to have so many minor releases
    that you need to use two digits, e.g. `1.17.0`.
  
  * For backward incompatilbe changes, increment the first component, `2.0.0`.
    If you've made backward incompatible changes that are likely to affect many 
    users. (Some subjectivity is needed here - if you've made a backward 
    incompatible change to a function that no one is likely to use then 
    a minor version might be acceptable. You need to use your judgement).
    
    You may also increment from `0.9.0` to `1.0.0` when you feel that the package
    is feature complete and the API is unlikely to change majorly in the future.

### Backward compatibility

The importance of backward compatability is directly proportional to the number of people using your package. When you start developing a package, I wouldn't worry too much about backwards compatibility. Sure, you'll break some code, but you don't want to be paralysed.  You are effectively trading your time for your users time. The harder you strive to be backward compatible, the harder it is to develop new features. It also gets harder to read and understand your code because it has to incorporate multiple paths for previous versions.

If you want to be more conservation, and avoid breaking existing code, you can use the following techniques:

* Don't immediately remove a function. First deprecate it, then flag it as 
  defunct, then remove it.

* Don't just immediately remove function arguments. Keep both arguments in the 
  function but print a warning when the wrong version is used.

* Avoid significant changes to the operation of a function. Instead create a 
  new function.

## Important files

Every package should contain a `README.md` that describes what the package does, and a `NEWS.md` that describes what's changed since the previous version. I recommend using markdown for these files, because it's useful for them to be readable in plain text (e.g. in emails) and in html (e.g. on github, in blog posts). I recommend using Github flavoured markdown, [gfm](#gfm), for these files.

### README.md {#readme}

The goal of the `README.md` is to answer the following questions:

* Why should I use it?
* How do I use it?
* How do I get it?

On github, the `README.md` will be rendered to html and displayed on the repo home page. 

I normally structure my `README` as follows:

1.  A paragraph that describes the high-level purpose of the package.
1.  An example showing how to use the package to solve a simple problem.
1.  An overview that describes the main components of the package. For more
    complex packages, this will point to vignettes for more details.
1.  Installation instructions, giving code that can be copied and pasted in R.

If you include an example in your `README` (a good idea!) you may want to generate it with Rmarkdown. Use these tips to make it as easy as possible:

* Use `format: md_document` in the yaml metadata to output a markdown file.

* Add `README.Rmd` to `.Rbuildignore` with 
  `devtools::add_ignore_file("README.Rmd")`.

* I recommend using the following knitr options:

    ```
    ```{r, echo = FALSE}
    knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
    ```
    ```

* Remember to re-knit `README.Rmd` each time you modify it.

### NEWS.md {#news}

The `README.md` is aimed at a potential new user of your package. The `NEWS.md` is aimed at existing users: it should list all changes in each last release of the package. There are a number formats you can use for package news, but I recommend `NEWS.md`. It's not supported by CRAN (so you'll need to run `devtools::add_build_ignore("NEWS.md")`), but it's well supported by github and is easy to re-purpose to other formats.

Organise your `NEWS.md` as follows:

* Use a level-one heading for each version: e.g. `# mypage 1.0`. The most
  recent version should go at the top.

* Each change should be included in a bulleted list. If you have a lot of 
  changes you might want to break them up using subheadings, `## Major changes`,
  `## Bug fixes` etc. I usually stick with a simple list until just before
  releasing the package when I'll reorgnise into sections, if needed.
  It's hard to know in advance exactly how many 

* If an item is related to an issue in github, include the issue number in
  parentheses, e.g. `(#10)`. If an item is related to a pull request, include 
  the pull request number and the author, e.g. `(#101, @hadley)`. Doing
  this makes it easy to navigate to the 

The main challenge with `NEWS.md` is getting into the habit of noting each change as it happens. 

## The check process {#release-check}

The automated checks provided by `R CMD check` are described in detail in [automated checking](#check). Here I'll focus on how the automated checks interact with CRAN. 

* You need to have run `R CMD check` and eliminated all `ERROR`s and `WARNING`s.
  You should have eliminated as many `NOTE`s as possible.
  
* You need to clearly communicate what checks you have run and why any potential 
  problems are in fact ok. 
  
I have adopted the convention of using a `cran-comments.md` file to record my communications with CRAN. It should be checked into git (so you can track it over time), and listed in `.Rbuildignore` (so its not included in the package submitted to CRAN). I recommend using markdown in the file, because it gives a standard way of laying out plain text, but the contents will never be rendered to another format, so you don't need to worry about sticking to it too closely.

The most important thing to understand about CRAN is that it's staffed by volunteers and its a lot of work. In a typical week, CRAN recieves around 130 packages, and there are only 3 volunteers to process all the submissions. Anything you can do to make their lives easier is appreciated. This means:

* Eliminate as many `NOTE`s as possible. Each `NOTE` requires human oversight,
  which is a precious commodity. If there are notes that you do not believe are 
  important, it is almost always easier to fix them (even if the fix is a bit 
  of a hack) than to persuade CRAN that they're ok. 
  
* Write your comments in way that's easy to scan, and easy to match up with
  `R CMD check`. Provide the CRAN maintainers with everything they need in 
  one place, even if it means repeating yourself.

Your `cran-comments.md` should be organised as follows:

* Start by listing how you have checked the package. What platforms and 
  what version of R did you use? In an ideal world you will have 
  checked with the latest development version of R and on at least two 
  platforms.

* If there are any `NOTE`s, copy and paste the message from `R CMD check` and 
  include a brief description of why you believe the NOTE is a false positive. 
  
* If there are CRAN packages that use your package, you need to run 
  `R CMD check` on all those packages, and 

For example, here's the relevent bit of `cran-comments.md` for a recent version of devtools:

```
The following notes were generated across my local OS X install, ubuntu running on travis-ci and win builder. Response to NOTEs across three platforms below.

* checking dependencies in R code ... NOTE
  Namespace in Imports field not imported from: ‘memoise’
  All declared Imports should be used.
  
  memoise is a build-time dependency.

* checking R code for possible problems ... NOTE
  Found the following calls to attach():
    File 'devtools/R/package-env.r':
      attach(NULL, name = pkg_env_name(pkg))
    File 'devtools/R/shims.r':
      attach(e, name = "devtools_shims", warn.conflicts = FALSE)

  These are needed because devtools simulates package loading, and hence
  needs to attach environments to the search path.
```

### R-devel

It's a good idea to check your package with the nightly version of R-devel. The checks are constantly changing and you have to keep up. The easiest way to do this is to: XYZ.

### Cross-platform checking

I highly recommend running `R CMD check` on at least two platforms:

* On windows: windows + linux
* On linux: linux + windows
* On OS X: os x + linux + windows

You can check packages on Windows using `build_win()`. This builds your package and submits it to the CRAN win-builder. 30-60 minutes after submission, you'll recieve and email which will point you to the check results. By default `build_win()` checks with both the release and development version of R. You can override this with the version parameter.

I hope that in the future we'll see more services like `build_win()` that allow you to check your package on multiple platforms without having to setup all the infrastructure yourself.

### Checking dependencies

If you are releasing a new version of an existing package, it's your responsibility to ensure that all packages that rely on your package continue to work.  

If any packages fail `R CMD check`, you should give package authors at least two weeks to fix the problem before you submit your package to CRAN.  After the two weeks is up, re-run the checks, and list any remaining failures in `cran-comments.md`. Each package should be accompanied  brief explanation - either that it's a false positive in `R CMD check` or a legitimate change in the API. Inform CRAN of your release process: "I advised all downstream packages maintainers of these problems two weeks ago". Here's an example from a recent release of httr:

```
I have also run R CMD check on downstream dependencies of httr. Results are 
available at R release: https://github.com/wch/checkresults/blob/master/httr/r-release.
Potential problems:

* Ecoengine: this appears to be a failure related to config on that machine,
  I couldn't reproduce locally, and it doesn't seem to be related to changes 
  in httr (the same problem exists with httr 0.4).
```

### CRAN policies

You must be familiar with [CRAN policies](http://cran.r-project.org/web/packages/policies.html). I recommending following the [CRAN Policy Watch](https://twitter.com/CRANPolicyWatch) twitter account which is automatically updated whenever the policies change. Alternatively you can look at the history at <https://github.com/eddelbuettel/crp/commits/master/texi>.

Most important points:

* Must have clearly identified IP holders in `DESCRIPTION`, have open source 
  license (so CRAN can distribute it) and not include any files that can not
  be generated from "source".

* It is vital that maintainer email address is stable. This is the only way
  that CRAN has to contact you, and they will remove your package from CRAN
  if there are problems and they can't get in touch with. Make sure it's 
  something that's likely to be around for a while, and that it's not heavily 
  filtered.

* Packages shouldn't make external changes without explicit user permission.
  Don't write to the file system, change options, install packages, quit R, 
  send information over the internet, open external software, etc.

## Release

Once you've run the automated checks on you need to upload your package to CRAN. I recommend using `devtools::release()` which asks a number of questions to make sure that you're ready, then builds, uploads and submits for you.

* Adding extra questions
* Comments to CRAN

On failure, make the suggested changes, update `cran-comments.md` describing what you did and why, and re-run `release()`. CRAN prefers you to not respond to their emails unless discussion is required.

Failures are frustrating, and the response you receive may be curt or downright insulting. Unfortunately no recourse is available, so you just have to develop a thick skin. You're not alone: even members of R-core have to go through the same gruelling process, and CRAN is no friendlier to them. Try not to get upset by the feedback. Ignore any ad hominen attacks, and simply respond to the technical content. 

Devtools comes with a small guarantee to make life a little more pleasant: If a CRAN maintainer is annoyed with you because devtools did something wrong, I will send you a hand-written apology card. Please send me an email with your address.

### Binary builds

After the package has been accepted by CRAN it will be built for each platform. It's possible this may uncover further errors.

## Prepare for next version {#post-release}

Once you've received confirmation that all checks have passed on all platforms, you have a couple of technical operations to do:

* Github release/`git tag`, so you can mark exactly what version of the code this release
  corresponds to. If you use github, use github releases - copy and paste
  the relevant portion of the NEWS file (converting to markdown if needed).

* bump version in `DESCRIPTION` and `NEWS` files. Use `.9000` prefix to 
  indicate that it's a development version.

* git commit and push

## Promotion {#promotion}

Then you need to publicise your package.  This is vitally important - for your hard work to be useful to someone, they need to know that it exists!

Start by writing a release announcement. This should be an Rmarkdown document that briefly describes what the package does (so people who haven't used it before can understand why they might care), and what's new in this version.  Start with what you've listed in `NEWS.md`, but the goal in the release announcement is not to be comprehensive, it's to highlight the most important new features.You can include a link at the end of the announcement to the full release notes so people can see all the changes. Where possible, I recommend showing examples of the new features: it's much easier to understand the benefit of a new feature if you can see it in action. 

There are a number of places you can include the announcemnt:

* If you have a blog, publish it there. I now publish all package release
  announcements on the [RStudio blog](http://blog.rstudio.org/author/hadleywickham/).
* If you use twitter, tweet about it.
* Send it to the r-packages mailing list.
