---
title: Releasing a package
layout: default
---

# Releasing a package

## Files


* the `NEWS` file describes the changes in each version of the package. Using
  the standard R format will allow you to take advantage of many automated
  tools for displaying changes between versions.

* the `README.md` file gives a general overview of your package, including why
  it's important. This text should be included in any package announcement, to
  help others understand why they might want to use your package.


## Source, binary and bundled packages

So far we've just described the structure of a source package: the development version of a package that lives on your computer. There are also two other types of package: bundled packages and binary packages.

A package __bundle__ is a compressed version of a package in a single file. By convention, package bundles in R use the extension `.tar.gz`. This is Linux convention indicating multiple files have been collapsed into a single file (`.tar`) and then compressed using gzip (`.gz`). The package bundle is useful if you want to manually distribute your package to another R package developer. It is not OS specific. You can use `devtools::build()` to make a package bundle.

If you want to distribute your package to another R user (i.e. someone who doesn't necessarily have the development tools installed) you need to make a __binary__ package. Like a package bundle, a binary package is a single file, but if you uncompress it, you'll see that the internal structure is a little different to a source package: 

* a `Meta/` directory contains a number of `Rds` files. These contain cached
  metadata about the package, like what topics the help files cover and
  parsed versions of the `DESCRIPTION` files. (If you want to look at what's
  in these files you can use `readRDS`)

* a `html/` directory contains some files needed for the HTML help.

* there are no `.R` files in the `R/` directory - instead there are three
  files that store the parsed functions in an efficient format. This is
  basically the result of loading all the R code and then saving the
  functions with `save`, but with a little extra metadata to make things as
  fast as possible.

* If you had any code in the `src/` directory there will now be a `libs/`
  directory that contains the results of compiling that code for 32 bit
  (`i386/`) and 64 bit (`x64`)

Binary packages are platform specific: you can't install a Windows binary package on a Mac or vice versa. You can use `devtools::build(binary = TRUE)` to make a package bundle.

An __installed__ package is just a binary package that's been uncompressed into a package library, described next.

## Package libraries

A library is a collection of installed packages. You can have multiple libraries on your computer and most people have at least two: one for the recommended packages that come with a base R install (like `base`, `stats` etc), and one library where the packages you've installed live. The default is to make that directory dependent on which version of R you have installed - that's why you normally lose all your packages when you reinstall R. If you want to avoid this behaviour, you can manually set the `R_LIBS` environmental variable to point somewhere else. `.libPaths()` tells you where your current libraries live.

When you use `library(pkg)` to load a package, R looks through each path in `.libPaths()` to see if a directory called `pkg` exists. 

## Installing packages

Package installation is the process whereby a source package gets converted into a binary package and then installed into your local package library.  There are a number of tools that automate this process:

* `install.packages()` installs a package from CRAN. Here CRAN takes care of
  making the binary package and so installation from CRAN basically is
  equivalent to downloading the binary package value and unzipping it in
  `.libPaths()[1]` (but you should never do this by hand because the process
  also does other checks)

* `devtools::install()` installs a source package from a directory on your
  computer.

* `devtools::install_github()` installs a package that someone has published
  on their [github](http://github) account. There are a number of similar
  functions that make it easy to install packages from other internet
  locations: `install_url`, `install_gitorious`, `install_bitbucket`, and so
  on.


## Checking

* from within R, run `roxygenise()`, or `devtools::document()` to update
  documentation

* from the command line, run `R CMD check`

Passing `R CMD check` is the most frustrating part of package development, and it usually takes some time the first time. Hopefully by following the tips elsewhere in this document you'll be in a good place to start – in particular, using roxygen and only exporting the minimal number of functions is likely to save a lot of work.

One place that it is frustrating to have problems with is the examples. If you discover a mistake, you need to fix it in the roxygen comments, rerun roxygen and then rerun `R CMD check`. The examples are one of the last things checked, so this process can be very time consuming, particularly if you have more than one bug. The `devtools` package contains a function, `run_examples` designed to make this somewhat less painful: all it does is run functions. It also has an optional parameter which tells it which function to start at - that way once you've discovered an error, you can rerun from just that file, not all the files that lead up to.

## Version numbers

The version number of your package increases with subsequent releases of a package, but it's more than just an incrementing counter -- the way the number changes with each release can convey information about what kind of changes are in the package.

An R package version can consist of a series of numbers, each separated with "." or "-". For example, a package might have a version 1.9. This version number is considered by R to be the same as 1.9.0, less than version 1.9.2, and all of these are less than version 1.10 (which is version "one point ten", not "one point one zero). R uses version numbers to determine whether package dependencies are satisfied. A package might, for example, import package `devtools (>= 1.9.2)`, in which case version 1.9 or 1.9.0 wouldn't work.

The version numbering advice here is inspired in part by [Semantic Versionsing](http://semver.org) and by the [X.Org](http://www.x.org/releases/X11R7.7/doc/xorg-docs/Versions.html) versioning schemes.

A version number consists of up to three numbers, _<major>_._<minor>_._<patch>_. For version number 1.9.2, 1 is the major number, 9 is the minor number, and 2 is the patch number. If your version number is 2.0, then implicit patch number is 0.

As your package evolves, the way the version number changes can reflect the type of changes in the code:

* The major number changes when there are incompatible API changes.
* The minor number changes when there are backward-compatible API changes.
* The patch number changes with backwards-compatible fixes.
* Additionally, during development between released versions, the package has a sub-patch version number of 99, as in 1.9.0.99. This makes it clear for users that they're using a development version of the package, as opposed to a formally released version.

Remember that these are guidelines. In practice, you might make changes that fall between the cracks. For example, if you make an API-incompatible change to a rarely-used part of your code, it may not deserve a major number change.

## Publishing on CRAN

Once you have passed the checking process, you need to upload your package to CRAN.  The checks will be run again with the latest development version of R, and on all platforms that R supports - this means that you should be prepare for more bugs to crop up.  Don't get excited too soon!

* update `NEWS`, checking that dates are correct. Use `devtools::show_news` to
  check that it's in the correct format.

* `R CMD build` then upload to CRAN: 
  `ftp -u ftp://cran.R-project.org/incoming/ package_name.tar.gz`

* send an email to `cran@r-project.org`, using the email address listed in the DESCRIPTION file. An example email would be something like: Hello, I just uploaded package name to CRAN. Please let me know if anything goes wrong. Thank you, Me. The subject line should be `CRAN submission PACKAGE VERSION`, this helps the CRAN maintainers keep track of the different submissions.

Once all the checks have passed you'll get a friendly email from the CRAN maintainer and you'll be ready to start publicising your package.

## Publicising

Once you've received confirmation that all checks have passed on all platforms, you have a couple of technical operations to do:

* `git tag`, so you can mark exactly what version of the code this release
  corresponds to

* bump version in `DESCRIPTION` and `NEWS` files

Then you need to publicise your package.  This is vitally important - for your hard work to be useful to someone, they need to know that it exists!

* send release announcement to `r-packages@stat.math.ethz.ch`. A release
  announcement should consist of a general introduction to your package (i.e.
  why should people care that you released a new version), and as well as
  what's new. I usually make these announcements by pasting together the
  package `README` and the appropriate section from the `NEWS`.

* announce on twitter, blog etc.

* Finally, don't forget to update your package webpage. If you don't have a
  package webpage – create one! There you can announce new versions, point to
  help resources, videos and talks about the package. If you're using github,
  I'd recommend using [github pages](http://pages.github.com/) to create the
  website.
  
