# Software development practices {#sec-sw-dev-practices}

```{r, echo = FALSE}
source("common.R")
status("drafting")
```

## Introduction

In this last part of the book, we zoom back out to consider development practices that can make you more productive and raise the quality of your work.
Here we'll discuss the use of version control and continuous integration.
In @sec-lifecycle we discuss how the nature of package maintenance varies over the lifecycle of a package.

You will notice that we recommend using certain tools:

-   An integrated development environment (IDE).
    In @sec-workflow101-rstudio-projects we encouraged the use of the RStudio IDE for package development work.
    That's what we document, since it's what we use and devtools is developed to work especially well with RStudio.
    But even if it's not RStudio, we strongly recommend working with an IDE that has specific support for R and R package development.

-   Version control.
    We strongly recommend the use of formal version control and, at this point in time, Git is the obvious choice.
    We say that based on Git's general prevalence and, specifically, its popularity within the R package ecosystem.
    In ??,
    we explain why we think version control is so important.

-   Hosted version control.
    We strongly recommend syncing your local Git repositories to a hosted service and, at this point in time, GitHub is the or, at least, "an" obvious choice.
    This the topic of ??.

-   Continuous integration and deployment, a.k.a. CI/CD (or just CI).
    This terminology comes from the general software engineering world and can sound somewhat grandiose or intimidating when applied to your personal R package.
    All this really means is that you set up specific package development tasks to happen automatically when you push new work to your hosted repository.
    Typically you'll want to run `R CMD check` and to re-build and deploy your package website.
    In ??
    we show how to do this with GitHub Actions.

You might think that these pro-style tools are overkill for someone who doesn't do software development for a living.
While we don't recommend forcing yourself to do everything above on day one of your first "hello world" project, we actually do believe these tools are broadly applicable for R package development.

The main reason is that these tools make it so much easier to do the right thing, e.g. to experiment, document, test, check, and collaborate.
By adopting a shared toolkit, part-time and newer package developers gain access to the same workflows used by experts.

## Git and GitHub {#sec-sw-dev-practices-git-github}

Planned content: general pep talk on the value of using version control and that, in 2022, Git is the obvious choice.
Once you're using Git, it makes sense to use a hosting service and, in 2022 in the R community, GitHub is the most popular choice and what the devtools ecosystem supports.

## Continuous integration {#sec-ci}

General intro to CI

## Checking after every commit with GitHub actions {#sec-gha}

If you're using GitHub, as we recommend, you should also use GitHub Actions.
GitHub Actions allow you to run code every time you push to GitHub.

To use GitHub Actions:

1.  Run `usethis::use_github_action_check_standard()` to set up a GitHub Action that runs `R CMD check` on Linux, Mac, and Windows.
    Literally, this adds a new file to your package, below `.github/workflows/.`

2.  Commit this new file and push to GitHub.

3.  Wait a few minutes to see the results in your email.

With this setup in place, `R CMD check` will be run every time you push to GitHub or whenever someone submits a pull request.
You'll find out about failures right away, which makes them easier to fix.
Using automated checks also encourages me to check more often locally, because I know if it fails I'll find out about it a few minutes later, often once I've moved on to a new problem.

### Other uses

Since GitHub Actions allows you to run arbitrary code, there are many other things that you can use it for:

-   Re-publishing a book website every time you make a change to the source.
    (Like this book!)

-   Building vignettes and publishing them to a website.

-   Automatically building a documentation website for your package.

Learn more about using GitHub Actions with R at <https://github.com/r-lib/actions/tree/master/examples>.
